'use strict';
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='familyTravelV11';
let db, city='da_nang', date='2027-01-11', tab='home', edit=false, map=null, filter='전체', selected=null, chat=[], busy=false;
let local={routes:{},notes:{},saved:[],custom:[]};
try{const v=JSON.parse(localStorage.getItem(KEY)||'null');if(v&&Array.isArray(v.custom)&&Array.isArray(v.saved)&&v.routes&&v.notes)local=v;}catch{}
const key=p=>p.city+':'+p.id, place=k=>[...db.places,...local.custom].find(p=>key(p)===k), cityInfo=()=>db.cities.find(c=>c.id===city), routeKey=()=>city+':'+date;
function save(){try{localStorage.setItem(KEY,JSON.stringify(local));return true;}catch{toast('이 기기에 저장할 수 없습니다. 여행 도구에서 파일로 백업해 주세요.');return false;}}
let toastTimer;function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').style.display='none',3500);}
function plans(){return db.itineraries.filter(i=>i.city===city&&i.label.startsWith('1/'+Number(date.slice(-2))+' '));}
function route(){return local.routes[routeKey()]??(plans()[0]?.placeIds||[]).map(id=>city+':'+id);}
function dateLabel(d){return new Date(d+'T12:00:00Z').toLocaleDateString('ko-KR',{month:'long',day:'numeric',weekday:'long',timeZone:'UTC'});}
function citySelect(){return `<label class="field mobile-city"><span class="sr">도시 선택</span><select id="city-select">${db.cities.map(c=>`<option value="${c.id}" ${city===c.id?'selected':''}>${c.nameKo}</option>`).join('')}</select></label>`;}
function changeCity(id){city=id;if(!cityInfo().dates.includes(date))date=cityInfo().dates[0];edit=false;filter='전체';render();}
function go(t){tab=t;edit=false;render();window.scrollTo(0,0);}
function render(){if(map){map.remove();map=null;}document.body.dataset.city=city;$('#main').className=tab==='ai'?'ai-main':'';$('#cities').innerHTML=db.cities.map(c=>`<button class="city ${c.id===city?'active':''}" data-city="${c.id}">${c.nameKo}<small>${c.dates[0].slice(5).replace('-','.')} — ${c.dates.at(-1).slice(5).replace('-','.')}</small></button>`).join('');$('#cities').querySelectorAll('button').forEach(b=>b.onclick=()=>changeCity(b.dataset.city));
const tabs=[['home','⌂','홈'],['schedule','▤','일정'],['map','◇','지도'],['saved','♡','저장'],['tools','☰','도구']];
$('#nav').innerHTML=tabs.map(([t,i,n])=>`<button data-tab="${t}" class="${tab===t?'active':''}" ${tab===t?'aria-current="page"':''}><span class="navicon" aria-hidden="true">${i}</span>${n}</button>`).join('');$('#nav').querySelectorAll('button').forEach(b=>b.onclick=()=>go(b.dataset.tab));
if(tab==='home')homeView();if(tab==='schedule')schedule();if(tab==='places'||tab==='saved')placesView();if(tab==='map')mapView();if(tab==='tools')toolsView();if(tab==='ai')aiView();
if($('#city-select'))$('#city-select').onchange=e=>changeCity(e.target.value);}
function homeView(){
  const days=Array.from({length:15},(_,i)=>`2027-01-${String(i+11).padStart(2,'0')}`);
  const transfers=Object.fromEntries(db.trip.route.map(r=>[r.date,r]));
  const routeAt=(cid,d)=>{const saved=local.routes[`${cid}:${d}`];if(saved)return saved.map(place).filter(Boolean);const ps=db.itineraries.filter(i=>i.city===cid&&i.label.startsWith('1/'+Number(d.slice(-2))+' '));return (ps[0]?.placeIds||[]).map(id=>place(cid+':'+id)).filter(Boolean);};
  const cityForDay=d=>db.cities.filter(c=>c.dates.includes(d));
  const rows=days.map((d,i)=>{const cs=cityForDay(d),transfer=transfers[d];let target=cs.at(-1)||db.cities[0];const points=cs.flatMap(c=>routeAt(c.id,d));const unique=points.filter((p,n,a)=>a.findIndex(x=>x.name===p.name)===n);const title=transfer?`${placeName(transfer.from)} → ${placeName(transfer.to)} 이동`:(db.itineraries.find(x=>x.city===target.id&&x.label.startsWith('1/'+Number(d.slice(-2))+' '))?.label.split('·').slice(1).join('·').trim()||target.role);return `<section class="trip-day"><div class="trip-day-head"><div><span>Day ${i+1}</span><h2>${dateLabel(d)}</h2></div><button class="textbtn" data-open-day="${d}" data-open-city="${target.id}">일정 보기</button></div><button class="trip-day-card" data-open-day="${d}" data-open-city="${target.id}"><span class="trip-city">${cs.map(c=>c.nameKo).join(' → ')}</span><b>${esc(title)}</b><small>${unique.slice(0,3).map(p=>p.name).join(' · ')}${unique.length>3?` 외 ${unique.length-3}곳`:''}</small></button></section>`;}).join('');
  $('#main').innerHTML=`<div class="trip-hero"><span class="eyebrow">2027. 1. 11 — 1. 25</span><h1>베트남 가족여행</h1><p>다낭에서 나트랑까지 · 14박 15일</p><div class="trip-stats"><span><b>4</b>도시</span><span><b>7→9</b>가족</span><span><b>105</b>장소</span></div></div><nav class="city-jump" aria-label="도시 일정 바로가기">${db.cities.map(c=>`<button data-jump-city="${c.id}"><b>${c.nameKo}</b><small>${c.dates[0].slice(5).replace('-','.')}—${c.dates.at(-1).slice(5).replace('-','.')}</small></button>`).join('')}</nav><div class="all-days"><h2>15일 전체 일정</h2>${rows}</div>`;
  document.querySelectorAll('[data-open-day]').forEach(b=>b.onclick=()=>{city=b.dataset.openCity;date=b.dataset.openDay;go('schedule');});
  document.querySelectorAll('[data-jump-city]').forEach(b=>b.onclick=()=>{changeCity(b.dataset.jumpCity);tab='schedule';render();window.scrollTo(0,0);});
}
function placeName(v){return({Incheon:'인천',Da_Nang:'다낭','Da Nang':'다낭','Diêu Trì / Quy Nhon':'꾸이년',Quy_Nhon:'꾸이년','Quy Nhon':'꾸이년',Tuy_Hoa:'뚜이호아','Tuy Hoa':'뚜이호아',Nha_Trang:'나트랑','Nha Trang':'나트랑'})[v]||v;}
function schedule(){const rows=route(), ps=plans();$('#main').innerHTML=`<div class="heading"><div><span class="eyebrow">2027. 1. 11 — 1. 25</span><h1>베트남 가족여행</h1><span class="muted">${cityInfo().nameKo} · ${city==='nha_trang'?'가족 9명':'가족 7명'}</span></div><button class="iconbtn" id="open-map" aria-label="일정 지도 보기">◇</button></div>${citySelect()}<div class="date-strip" aria-label="날짜 선택">${cityInfo().dates.map(d=>`<button class="date ${d===date?'active':''}" data-date="${d}" aria-label="${dateLabel(d)}" aria-pressed="${d===date}">${new Date(d+'T12:00Z').toLocaleDateString('ko',{weekday:'short',timeZone:'UTC'})}<b>${Number(d.slice(-2))}</b></button>`).join('')}</div><div class="day-head"><h2>Day ${Number(date.slice(-2))-10} <small>${date.slice(5).replace('-','.')} · ${cityInfo().nameKo}</small></h2><button class="textbtn" id="edit">${edit?'완료':'편집'}</button></div>${ps.length>1?`<label class="field plan-select"><span>일정안 선택</span><select id="plan">${ps.map(p=>`<option value="${p.id}">${esc(p.label)}</option>`).join('')}<option value="custom" ${local.routes[routeKey()]?'selected':''}>내가 편집한 일정</option></select></label>`:''}<div class="timeline">${rows.map((k,i)=>{const p=place(k);return p?`<div class="stop"><span class="dot">${i+1}</span><button class="card card-media" data-place="${esc(k)}">${cardPhoto(p)}<span class="card-copy"><b>${esc(p.name)}</b><small>${esc(p.cat)}${p.stay?' · '+esc(p.stay):''}</small></span></button>${edit?`<div class="edit-row"><button data-move="${i}" data-delta="-1" ${i===0?'disabled':''} aria-label="${esc(p.name)} 위로">↑ 위로</button><button data-move="${i}" data-delta="1" ${i===rows.length-1?'disabled':''}>↓ 아래로</button><button class="danger" data-remove="${i}">일정에서 빼기</button></div>`:''}</div>`:'';}).join('')}</div>${!rows.length?'<div class="empty">아직 등록된 일정이 없습니다.<br>장소를 추가해 하루를 구성해 보세요.</div>':''}${local.notes[routeKey()]?`<div class="memo">${esc(local.notes[routeKey()])}</div>`:''}<div class="actions"><button class="btn" id="add">＋ 장소 추가</button><button class="btn" id="memo">메모 ${local.notes[routeKey()]?'편집':'추가'}</button></div>${ps[0]?.note?`<details class="section"><summary>기존 일정 메모</summary><p class="notice">${esc(ps[0].note)}</p></details>`:''}<p class="notice">기존에 정리한 일정안입니다. 방문 확정을 뜻하지 않으며, 가족 상황에 맞게 편집할 수 있습니다.</p>`;
$('#open-map').onclick=()=>go('map');$('#edit').onclick=()=>{edit=!edit;render();};$('#add').onclick=addPlace;$('#memo').onclick=editMemo;document.querySelectorAll('[data-date]').forEach(b=>b.onclick=()=>{date=b.dataset.date;edit=false;render();});bindPlaces();document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{const a=[...route()];a.splice(+b.dataset.remove,1);local.routes[routeKey()]=a;save();render();});document.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>{const a=[...route()],i=+b.dataset.move,j=i+(+b.dataset.delta);[a[i],a[j]]=[a[j],a[i]];local.routes[routeKey()]=a;save();render();});if($('#plan'))$('#plan').onchange=e=>{if(e.target.value==='custom')return;const apply=()=>{local.routes[routeKey()]=db.itineraries.find(p=>p.id===e.target.value).placeIds.map(id=>city+':'+id);save();closeSheet();render();};openSheet('일정안 변경',`<p>선택한 일정안으로 이 날짜의 장소 순서를 교체할까요? 메모와 저장한 장소는 유지됩니다.</p>`,`<button class="btn" id="cancel-plan">취소</button><button class="btn primary" id="apply-plan">교체</button>`);$('#cancel-plan').onclick=()=>{closeSheet();render();};$('#apply-plan').onclick=apply;};}
function bindPlaces(){document.querySelectorAll('[data-place]').forEach(b=>b.onclick=()=>quick(b.dataset.place));}
function openSheet(title,body,foot=''){const d=$('#sheet');d.innerHTML=`<div class="sheet-head"><h2 id="sheet-title">${esc(title)}</h2><button class="iconbtn" id="close-sheet" aria-label="닫기">×</button></div><div class="sheet-body">${body}</div>${foot?`<div class="sheet-foot">${foot}</div>`:''}`;$('#close-sheet').onclick=closeSheet;if(!d.open)d.showModal();d.scrollTop=0;}
function closeSheet(){$('#sheet').close();selected=null;}
function mapsURL(p){return 'https://www.google.com/maps/dir/?api=1&destination='+encodeURIComponent(p.lat+','+p.lng);}
function safeLink(url,label){return `<a class="btn" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${label}</a>`;}
function localPhotoPath(p){return p?.photoFile||(`photos/${p.city}/${p.id}.jpg`);}
function photoFigure(p){if(!p)return '';const ph=p.photo||{},localSrc=localPhotoPath(p),fallback=ph.url||'';return `<figure class="place-photo"><img src="${esc(localSrc)}" data-fallback="${esc(fallback)}" alt="${esc(p.name)} 사진" loading="lazy" onload="const c=this.closest('figure').querySelector('figcaption');if(c)c.style.display=this.dataset.tried==='1'?'block':'none'" onerror="if(this.dataset.fallback&&this.dataset.tried!=='1'){this.dataset.tried='1';this.src=this.dataset.fallback}else{this.closest('figure').classList.add('photo-error')}"><figcaption ${fallback?'':'style="display:none"'}>사진: ${esc(ph.credit||ph.provider||'Wikimedia Commons')} · ${esc(ph.license||'라이선스 확인')} ${ph.source?`· <a href="${esc(ph.source)}" target="_blank" rel="noopener noreferrer">출처</a>`:''}</figcaption></figure>`;}
function cardPhoto(p){if(!p)return '';const localSrc=localPhotoPath(p),fallback=p?.photo?.url||'';return `<img class="card-thumb" src="${esc(localSrc)}" data-fallback="${esc(fallback)}" alt="" loading="lazy" onerror="if(this.dataset.fallback&&this.dataset.tried!=='1'){this.dataset.tried='1';this.src=this.dataset.fallback}else{this.remove()}">`;}
function quick(k){const p=place(k);if(!p)return;openSheet('장소 간편 보기',`${photoFigure(p)}<span class="eyebrow">${db.cities.find(c=>c.id===p.city)?.nameKo||''} · ${esc(p.cat)}</span><h3 class="detail-title">${esc(p.name)}</h3><p class="muted">${esc(p.role||p.en)}</p><button class="btn" id="details" style="width:100%">장소 상세 정보 보기 ›</button>`,`<button class="btn" id="save-place">${local.saved.includes(k)?'♥ 저장됨':'♡ 저장'}</button>${safeLink(mapsURL(p),'길찾기')}`);$('#details').onclick=()=>details(k);$('#save-place').onclick=()=>{local.saved=local.saved.includes(k)?local.saved.filter(x=>x!==k):[...local.saved,k];save();quick(k);if(tab==='saved')render();};}
function details(k){const p=place(k);openSheet('장소 상세',`${photoFigure(p)}<span class="eyebrow">${esc(p.cat)}</span><h3 class="detail-title">${esc(p.name)}</h3><p class="muted">${esc(p.en)}</p>${[['장소 소개',p.desc],['가족 여행 메모',p.tip],['주소',p.address],['이용 정보 · 기존 기록',[p.hours,p.stay].filter(Boolean).join(' · ')]].filter(([,v])=>v).map(([t,v])=>`<div class="info"><b>${t}</b><p>${esc(v)}</p></div>`).join('')}<p class="notice section">기존 자료의 정보를 그대로 옮겼습니다. 영업시간·가격의 최신 여부를 확인한 것은 아닙니다.</p><button class="btn" id="copy-address">주소 복사</button>`,`<button class="btn" id="back-quick">간편 보기</button>${safeLink(mapsURL(p),'길찾기')}`);$('#back-quick').onclick=()=>quick(k);$('#copy-address').onclick=async()=>{try{await navigator.clipboard.writeText(p.address||p.name);toast('주소를 복사했습니다.');}catch{toast('복사가 제한되어 있습니다. 주소 텍스트를 길게 눌러 복사해 주세요.');}};}
function editMemo(){openSheet('하루 메모',`<label class="field"><span>${dateLabel(date)}</span><textarea id="day-memo" maxlength="2000">${esc(local.notes[routeKey()]||'')}</textarea></label>`,`<button class="btn primary" id="save-memo">저장</button>`);$('#save-memo').onclick=()=>{local.notes[routeKey()]=$('#day-memo').value.trim();save();closeSheet();render();};}
function placesView(){const saved=tab==='saved';$('#main').innerHTML=`<div class="heading"><div><span class="eyebrow">${cityInfo().nameKo}</span><h1>${saved?'저장한 장소':'어디로 가볼까요?'}</h1></div></div>${citySelect()}<label class="field"><span class="sr">장소 검색</span><input id="place-search" type="search" placeholder="장소 이름이나 음식으로 찾기"></label><div class="filter-row">${['전체','가볼 곳','식사·카페','생활'].map(f=>`<button class="pill ${f===filter?'active':''}" data-filter="${f}">${f}</button>`).join('')}</div><div class="place-list" id="place-list"></div>`;const update=()=>{const q=$('#place-search').value.trim().toLowerCase();const result=[...db.places,...local.custom].filter(p=>p.city===city&&(!saved||local.saved.includes(key(p)))&&JSON.stringify([p.name,p.en,p.desc,p.cat]).toLowerCase().includes(q)&&(filter==='전체'||(filter==='식사·카페'?['음식','로컬','카페'].includes(p.cat):filter==='생활'?['숙소','교통','마사지','세탁','쇼핑'].includes(p.cat):!['음식','로컬','카페','숙소','교통','마사지','세탁','쇼핑'].includes(p.cat))));$('#place-list').innerHTML=result.map(p=>`<button class="card card-media" data-place="${esc(key(p))}">${cardPhoto(p)}<span class="card-copy"><b>${esc(p.name)}</b><small>${esc(p.cat)} · ${esc(p.role||p.en)}</small></span></button>`).join('')||'<div class="empty">조건에 맞는 장소가 없습니다.</div>';bindPlaces();};$('#place-search').oninput=update;document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));update();});update();}
function addPlace(){selected=null;const cityName=cityInfo().nameKo;openSheet(`${cityName} 일정에 장소 추가`,`<span class="eyebrow">${dateLabel(date)}</span><label class="field"><span>${cityName} 장소 검색</span><input id="add-search" type="search" placeholder="기존 장소 이름 검색"></label><div id="add-results"></div><p class="notice section">기존 장소 105곳에서 먼저 찾습니다. 없는 장소는 온라인으로 검색할 수 있습니다.</p><button class="btn" id="external-search">새 장소 온라인 검색</button>`,`<button class="btn primary" id="confirm-add" disabled>장소를 선택해 주세요</button>`);const update=()=>{const q=$('#add-search').value.trim().toLowerCase();const rows=[...db.places,...local.custom].filter(p=>p.city===city&&(p.name+' '+p.en).toLowerCase().includes(q));$('#add-results').innerHTML=rows.map(p=>`<button class="result" data-select="${esc(key(p))}"><b>${esc(p.name)}</b><small>${esc(p.cat)}</small></button>`).join('')||'<p>검색 결과가 없습니다.</p>';document.querySelectorAll('[data-select]').forEach(b=>b.onclick=()=>{selected=b.dataset.select;document.querySelectorAll('[data-select]').forEach(x=>x.classList.toggle('selected',x===b));$('#confirm-add').disabled=false;$('#confirm-add').textContent='이 일정에 추가';});};$('#add-search').oninput=update;$('#external-search').onclick=externalSearch;$('#confirm-add').onclick=()=>{if(!selected)return;if(route().includes(selected)){toast('이미 이 일정에 있는 장소입니다.');return;}local.routes[routeKey()]=[...route(),selected];save();closeSheet();render();toast('일정에 장소를 추가했습니다.');};update();}
function externalSearch(){const cid=city,c=cityInfo();let found=[];selected=null;openSheet('새 장소 찾기',`<label class="field"><span>${c.nameKo} 장소 검색</span><input id="online-query" placeholder="장소명 입력" maxlength="150"></label><button class="btn" id="search-online">검색</button><div id="online-results" aria-live="polite"></div><label class="field section"><span>분류</span><select id="online-cat">${['관광','음식','카페','숙소','쇼핑','세탁','마사지','교통'].map(v=>`<option>${v}</option>`).join('')}</select></label><label class="field"><span>간단한 메모</span><textarea id="online-memo" maxlength="1000"></textarea></label><p class="notice">OpenStreetMap 검색 결과입니다. 주소가 방문하려는 지역과 맞는지 확인해 주세요.</p>`,`<button class="btn primary" id="online-save" disabled>장소를 선택해 주세요</button>`);$('#search-online').onclick=async()=>{const q=$('#online-query').value.trim();if(!q)return;const button=$('#search-online');button.disabled=true;$('#online-results').textContent='검색 중…';selected=null;$('#online-save').disabled=true;try{const u=new URL('https://nominatim.openstreetmap.org/search');u.search=new URLSearchParams({format:'jsonv2',q:q+', '+c.name+', Vietnam',countrycodes:'vn',limit:'5','accept-language':'ko,en'});const r=await fetch(u,{signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error();found=await r.json();if(!$('#online-results'))return;$('#online-results').innerHTML=found.map((p,i)=>`<button class="result" data-online="${i}"><b>${esc(p.name||q)}</b><small>${esc(p.display_name)}</small></button>`).join('')||'<p>검색 결과가 없습니다. 다른 이름으로 검색해 주세요.</p>';document.querySelectorAll('[data-online]').forEach(b=>b.onclick=()=>{selected=+b.dataset.online;document.querySelectorAll('[data-online]').forEach(x=>x.classList.toggle('selected',x===b));$('#online-save').disabled=false;$('#online-save').textContent='장소 저장하고 일정에 추가';});}catch{if($('#online-results'))$('#online-results').textContent='온라인 검색에 연결하지 못했습니다. 기존 장소 검색은 계속 이용할 수 있습니다.';}finally{button.disabled=false;}};$('#online-save').onclick=()=>{if(selected===null)return;const x=found[selected];const p={id:'custom-'+crypto.randomUUID(),city:cid,name:x.name||$('#online-query').value.trim(),en:x.name||'',lat:Number(x.lat),lng:Number(x.lon),address:x.display_name,cat:$('#online-cat').value,tip:$('#online-memo').value.trim(),desc:'사용자가 온라인 검색으로 추가한 장소',custom:true};local.custom.push(p);local.routes[routeKey()]=[...route(),key(p)];save();closeSheet();render();toast('새 장소를 저장했습니다.');};}
function mapView(){$('#main').innerHTML=`<div class="heading"><div><span class="eyebrow">${dateLabel(date)}</span><h1>${cityInfo().nameKo} 동선</h1></div><button class="textbtn" id="back-schedule">일정 보기</button></div>${citySelect()}<p class="map-warning">번호는 일정 순서입니다. 선은 실제 도로 경로가 아니며, 이동 안내는 장소의 길찾기를 이용해 주세요.</p><div class="map" id="map"></div><div class="actions"><button class="btn" id="all-points">도시의 모든 장소</button><button class="btn" id="route-points">일정 장소만</button></div><div id="map-order"></div>`;$('#back-schedule').onclick=()=>go('schedule');const draw=all=>{if(map){map.remove();map=null;}if(!window.L){$('#map').innerHTML='<div class="empty">지도를 불러오지 못했습니다. 인터넷 연결을 확인해 주세요. 일정과 장소 정보는 계속 볼 수 있습니다.</div>';return;}const rows=all?[...db.places,...local.custom].filter(p=>p.city===city):route().map(place).filter(Boolean);$('#map-order').innerHTML=all?'':`<h2 class="map-order-title">방문 순서</h2><div class="map-order-list">${rows.map((p,i)=>`<button data-place="${esc(key(p))}"><span>${i+1}</span><b>${esc(p.name)}</b></button>`).join('')}</div>`;bindPlaces();map=L.map('map');L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors',maxZoom:19}).addTo(map);const coords=[];rows.forEach((p,i)=>{if(!Number.isFinite(p.lat)||!Number.isFinite(p.lng))return;coords.push([p.lat,p.lng]);const marker=L.marker([p.lat,p.lng],{icon:L.divIcon({className:'map-marker',html:String(i+1),iconSize:[32,32]})}).addTo(map);marker.bindTooltip(esc(p.name),{permanent:false,direction:'top'}).on('click',()=>quick(key(p)));});if(coords.length){map.fitBounds(coords,{paddingTopLeft:[55,75],paddingBottomRight:[55,55],maxZoom:14});if(!all)L.polyline(coords,{color:'#2579ef',weight:3,dashArray:'8 9'}).addTo(map);}else{const p=db.places.find(p=>p.city===city);map.setView([p.lat,p.lng],12);}};$('#all-points').onclick=()=>draw(true);$('#route-points').onclick=()=>draw(false);draw(false);}
function toolsView(){$('#main').innerHTML=`<div class="heading"><div><span class="eyebrow">필요할 때 꺼내 보는</span><h1>여행 도구</h1></div></div>${citySelect()}<div class="place-list"><button class="card" id="ai-open"><b>✦ AI 여행 비서</b><small>선택한 도시와 날짜의 동선 상담</small></button><button class="card" id="weather"><b>현재 날씨</b><small>${cityInfo().nameKo} · 여행 날짜의 예보와 구분해 표시</small></button></div><div id="weather-result" class="weather-result" aria-live="polite"></div><details class="section"><summary>숙소·긴급 연락처 · 기존 기록</summary>${db.safety.accommodations.filter(p=>p.city===city).map(p=>`<div class="info"><b>${esc(p.name)}</b><p>${esc(p.address)}</p></div>`).join('')}${db.safety.emergencyNumbers.map(p=>`<div class="info"><b>${esc(p.label)}</b><a href="tel:${esc(p.number)}">${esc(p.number)}</a></div>`).join('')}<p class="notice">기존 파일의 연락처입니다. 이번 제작에서 최신 여부를 재확인하지 않았습니다.</p></details><details class="section"><summary>내 일정 백업·복원</summary><p class="notice">편집한 일정·메모·저장 장소는 이 기기에 저장됩니다. 가족 휴대폰과 자동 동기화되지 않습니다. 백업 파일을 전달한 뒤 다른 기기에서 복원할 수 있습니다.</p><div class="actions"><button class="btn" id="export">백업 내려받기</button><button class="btn" id="import">백업 복원</button></div><input type="file" id="import-file" accept=".json" hidden></details><p class="notice">v11.4.1 시범판 · 기존 장소 ${db.places.length}곳 · 로컬 사진 슬롯 ${db.places.length}곳 · 외부 대체사진 13곳<br>기존 앱의 기기별 추가 장소·편집 일정은 아직 자동 이전하지 않습니다.</p>`;$('#ai-open').onclick=()=>go('ai');$('#weather').onclick=weather;$('#export').onclick=()=>{const blob=new Blob([JSON.stringify({version:11,data:local},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='family-trip-v11-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};$('#import').onclick=()=>$('#import-file').click();$('#import-file').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>5e6)throw Error();const v=JSON.parse(await file.text());if(v.version!==11||!v.data||!Array.isArray(v.data.custom)||!Array.isArray(v.data.saved)||!v.data.routes||!v.data.notes)throw Error();if(!v.data.custom.every(p=>db.cities.some(c=>c.id===p.city)&&typeof p.id==='string'&&typeof p.name==='string'&&Number.isFinite(p.lat)&&Number.isFinite(p.lng))||!Object.values(v.data.routes).every(a=>Array.isArray(a)&&a.every(k=>typeof k==='string'))||!Object.values(v.data.notes).every(n=>typeof n==='string')||!v.data.saved.every(k=>typeof k==='string'))throw Error();openSheet('백업 복원','<p>이 기기의 v11 편집 내용을 백업 파일로 교체할까요? 기존 v10 데이터는 변경하지 않습니다.</p>','<button class="btn primary" id="restore">교체하고 복원</button>');$('#restore').onclick=()=>{local=v.data;save();closeSheet();render();toast('복원했습니다.');};}catch{toast('올바른 v11 백업 파일이 아닙니다.');}};}
let liveWeather=null;
function weatherCodeLabel(code){
  if(code===0)return '맑음';
  if([1,2,3].includes(code))return '구름 조금';
  if([45,48].includes(code))return '안개';
  if([51,53,55,56,57].includes(code))return '이슬비';
  if([61,63,65,66,67].includes(code))return '비';
  if([71,73,75,77].includes(code))return '눈';
  if([80,81,82].includes(code))return '소나기';
  if([85,86].includes(code))return '눈 소나기';
  if([95,96,99].includes(code))return '뇌우';
  return '날씨 정보';
}
async function fetchWeatherForCity(cid=city){
  const p=db.places.find(p=>p.city===cid);
  if(!p)throw Error();
  const u='https://api.open-meteo.com/v1/forecast?'+new URLSearchParams({latitude:p.lat,longitude:p.lng,current:'temperature_2m,precipitation,weather_code',timezone:'Asia/Ho_Chi_Minh'});
  const r=await fetch(u,{signal:AbortSignal.timeout(10000)});
  if(!r.ok)throw Error();
  const d=await r.json();
  liveWeather={cityId:cid,fetchedAt:new Date().toISOString(),current:d.current};
  return liveWeather;
}
async function weather(){
  const target=$('#weather-result');
  if(!target)return;
  target.textContent='현재 날씨 확인 중…';
  try{
    const w=await fetchWeatherForCity(city),c=w.current;
    target.innerHTML=`<div class="memo">${esc(c.time.replace('T',' '))} · 베트남 현지 시각<br>${esc(weatherCodeLabel(c.weather_code))} · 기온 ${esc(c.temperature_2m)}℃ · 강수 ${esc(c.precipitation)}mm<br><small>Open-Meteo 현재 관측·모델 정보입니다. 2027년 여행일 예보가 아닙니다.</small></div>`;
  }catch{target.textContent='현재 날씨를 불러오지 못했습니다. 잠시 후 다시 확인해 주세요.';}
}
function aiFamilyLabel(){return city==='nha_trang'?db.trip.travelers.nhaTrangSegment:db.trip.travelers.defaultSegment;}
function aiFamilySummary(){return city==='nha_trang'?'가족 9명':'가족 7명';}
function aiQuickPrompts(){return [
  '이 일정이 가족에게 무리 없는지 이동량과 휴식 기준으로 점검해줘.',
  '현재 방문 순서에서 이동 동선을 더 줄일 수 있는지 봐줘.',
  '아이들과 함께 움직일 때 식사와 휴식 타이밍을 제안해줘.',
  '비가 오거나 너무 더울 때 바꾸기 좋은 대안을 제안해줘.',
  '오늘 일정에서 꼭 확인해야 할 준비물과 주의사항을 정리해줘.'
];}
function aiView(){
  const rows=route().map(place).filter(Boolean),transfer=db.trip.route.find(r=>r.date===date),w=liveWeather?.cityId===city?liveWeather.current:null;
  const routeNames=rows.length?rows.map((p,i)=>`${i+1}. ${esc(p.name)}`).join(' → '):'등록된 일정 없음';
  const weatherText=w?`${weatherCodeLabel(w.weather_code)} · ${w.temperature_2m}℃ · 강수 ${w.precipitation}mm`:'아직 불러오지 않음';
  $('#main').innerHTML=`<div class="heading ai-heading"><div><span class="eyebrow">${cityInfo().nameKo} · ${dateLabel(date)}</span><h1>AI 여행 비서</h1></div><button class="textbtn" id="ai-back">도구로</button></div>
  <div class="ai-context"><div class="ai-context-head"><div><span class="eyebrow">AI가 참고하는 오늘의 정보</span><b>Day ${Number(date.slice(-2))-10} · ${cityInfo().nameKo}</b></div><button class="textbtn ai-weather-btn" id="ai-weather">${w?'날씨 새로고침':'현재 날씨 추가'}</button></div><div class="ai-context-grid"><span><small>가족</small><b>${esc(aiFamilySummary())}</b></span><span><small>일정</small><b>${rows.length}곳</b></span><span class="weather-summary"><small>날씨</small><b>${w?`${esc(weatherCodeLabel(w.weather_code))} · ${esc(w.temperature_2m)}℃`:'미확인'}</b></span></div><p class="ai-route"><b>오늘 동선</b> ${routeNames}</p>${transfer?`<p class="ai-transfer">이동일 · ${esc(placeName(transfer.from))} → ${esc(placeName(transfer.to))}${transfer.note?' · '+esc(transfer.note):''}</p>`:''}</div>
  <div class="ai-quick"><div class="ai-quick-head"><h2>빠르게 물어보기</h2><button class="textbtn" id="ai-clear" ${chat.length?'':'disabled'}>대화 지우기</button></div><div class="ai-chips">${aiQuickPrompts().map((q,i)=>`<button class="ai-chip" data-ai-prompt="${i}" ${busy?'disabled':''}>${['일정 강도','동선 최적화','식사·휴식','날씨 대안','준비물'][i]}</button>`).join('')}</div></div>
  <p class="notice ai-notice">현재 일정·가족 구성·저장 장소를 함께 전달합니다. 날씨를 추가하면 AI도 참고합니다.</p>
  <div class="chat" id="chat" aria-live="polite"></div><form class="chat-form" id="chat-form"><input id="question" placeholder="이 동선이 가족에게 무리 없을까?" aria-label="AI 질문" maxlength="700" required><button class="btn primary" id="send" ${busy?'disabled':''}>전송</button></form>
  <details class="section ai-settings"><summary>AI 연결 설정</summary><label class="field"><span>기존 Worker 연결 주소</span><input id="endpoint" type="url"></label><button class="btn" id="endpoint-save">이 기기에 저장</button></details>`;
  $('#ai-back').onclick=()=>go('tools');
  $('#endpoint').value=localStorage.getItem('travelAiEndpoint')||window.TRAVEL_AI_CONFIG?.endpoint||'';
  $('#endpoint-save').onclick=()=>{const v=$('#endpoint').value.trim();try{if(new URL(v).protocol!=='https:')throw Error();localStorage.setItem('travelAiEndpoint',v);toast('연결 주소를 저장했습니다.');}catch{toast('https:// 주소를 확인해 주세요.');}};
  $('#ai-weather').onclick=async()=>{const b=$('#ai-weather');b.disabled=true;b.textContent='확인 중…';try{await fetchWeatherForCity(city);toast('현재 날씨를 AI에 전달할 준비가 됐습니다.');}catch{toast('현재 날씨를 불러오지 못했습니다.');}aiView();};
  $('#ai-clear').onclick=()=>{if(!chat.length)return;chat=[];aiView();toast('AI 대화를 지웠습니다.');};
  document.querySelectorAll('[data-ai-prompt]').forEach(b=>b.onclick=()=>sendAIQuestion(aiQuickPrompts()[+b.dataset.aiPrompt]));
  renderChat();
  $('#chat-form').onsubmit=e=>{e.preventDefault();sendAIQuestion($('#question').value.trim());};
}
async function sendAIQuestion(q){
  if(busy||!q)return;
  const endpoint=localStorage.getItem('travelAiEndpoint')||window.TRAVEL_AI_CONFIG?.endpoint;
  if(!endpoint){toast('AI 연결 주소를 먼저 설정해 주세요.');return;}
  const cid=city,day=date,history=chat.slice(-8),rows=route().map(place).filter(Boolean),transfer=db.trip.route.find(r=>r.date===day);
  chat.push({role:'user',content:q});
  if($('#question'))$('#question').value='';
  busy=true;
  document.querySelectorAll('#send,[data-ai-prompt]').forEach(b=>b.disabled=true);
  renderChat();
  try{
    const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},signal:AbortSignal.timeout(30000),body:JSON.stringify({message:q,history,context:{appVersion:'11.4.1-preview',currentCity:cid,currentDate:day,travelDayNumber:Number(day.slice(-2))-10,currentCityName:cityInfo().nameKo,familyLabel:aiFamilyLabel(),trip:db.trip,family:db.trip.travelers,cities:db.cities,currentCityInfo:cityInfo(),currentRoute:rows,currentRouteNote:local.notes[routeKey()]||'',currentTransfer:transfer||null,plannedItineraries:plans(),cityPlaces:[...db.places,...local.custom].filter(p=>p.city===cid),savedPlaces:local.saved.map(place).filter(p=>p?.city===cid),safety:db.safety,liveWeather:liveWeather?.cityId===cid?liveWeather:null}})});
    if(!r.ok)throw Error();
    const d=await r.json();
    chat.push({role:'assistant',content:d.answer||'표시할 답변이 없습니다.'});
  }catch{chat.push({role:'assistant',content:'AI 서버에 연결하지 못했습니다. 기존 Worker 주소와 인터넷 연결을 확인해 주세요.'});}
  finally{
    busy=false;
    document.querySelectorAll('#send,[data-ai-prompt]').forEach(b=>b.disabled=false);
    renderChat();
  }
}
function renderChat(){
  if(!$('#chat'))return;
  $('#chat').innerHTML=chat.map((m,i)=>`<div class="chat-message ${m.role==='user'?'user':''}"><div class="bubble ${m.role==='user'?'user':''}">${esc(m.content)}</div>${m.role==='assistant'?`<button class="chat-copy" data-chat-copy="${i}">답변 복사</button>`:''}</div>`).join('')+(busy?'<div class="chat-message"><div class="bubble">여행 일정을 살펴보고 있습니다…</div></div>':'');
  document.querySelectorAll('[data-chat-copy]').forEach(b=>b.onclick=async()=>{try{await navigator.clipboard.writeText(chat[+b.dataset.chatCopy]?.content||'');toast('AI 답변을 복사했습니다.');}catch{toast('복사가 제한되어 있습니다.');}});
}
async function init(){try{const names=['trip','cities','places','itineraries','safety'];const values=await Promise.all(names.map(async n=>{const r=await fetch('data/'+n+'.json');if(!r.ok)throw Error();return r.json();}));db=Object.fromEntries(names.map((n,i)=>[n,values[i]]));const requested=new URLSearchParams(location.search).get('city');if(db.cities.some(c=>c.id===requested))city=requested;date=cityInfo().dates[0];render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});}catch{$('#main').innerHTML='<h1>일정을 불러오지 못했습니다</h1><p>인터넷 연결을 확인하고 다시 열어 주세요. 파일을 직접 열었다면 GitHub Pages 또는 웹 서버에서 실행해 주세요.</p><button class="btn" onclick="location.reload()">다시 시도</button>';}}
init();
